{% set name = "libdrs_f" %}
{% set version = "3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/UV-CDAT/libdrs/archive/v2.12.tar.gz
  sha256: d44a71f7903ce75c3c1d3839564fba2e7275a88e2353a5d2197280ec938752f5

build:
  number: 0
  skip: True  # [win] 

requirements:
  build:
    - g2clib
    - libcdms
    - libpng >=1.6.28,<1.7
    - gcc 
  run:
    - g2clib
    - libcdms
    - libpng >=1.6.28,<1.7
    - libgfortran

test:
  commands:
    - test -f $PREFIX/lib/libdrsfortran.a 

about:
  home:  http://uvcdat.llnl.gov
  license: CCLRC
  summary: 'Data Retrieval and Storage DRS software Fortran library'
  description: |            
    libdrs is suitable for the data generated and used in climate model research. 
    It is oriented toward use with models generating very large datasets on 
    supercomputers, as well as with graphics workstations used for analysis and 
    display of smaller subsets of data. 
  dev_url: http://github.com/UV-CDAT/libdrs

extra:
  recipe-maintainers:
    - dnadeau4
    - doutriaux1
