{% set name = "libdrs_f" %}
{% set version = "3.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/CDAT/libdrs/archive/v{{ version }}.tar.gz
  sha256: 90e10191116a78228739276078a0ddcf0d6458516f192e9e79fecb2beeceb3fa

build:
  number: 3
  skip: True  # [win]

requirements:

  build:
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
  host:
    - g2clib
    - libcdms
    - libpng
  run:
    - g2clib
    - libcdms
    - libpng

test:
  commands:
    - test -f $PREFIX/lib/libdrsfortran.a

about:
  home:  http://uvcdat.llnl.gov
  license: BSD
  license_file: bsd-3-clause.txt
  summary: 'Data Retrieval and Storage DRS software Fortran library'
  description: |
    libdrs is suitable for the data generated and used in climate model research.
    It is oriented toward use with models generating very large datasets on
    supercomputers, as well as with graphics workstations used for analysis and
    display of smaller subsets of data.
  dev_url: http://github.com/CDAT/libdrs

extra:
  recipe-maintainers:
    - dnadeau4
    - doutriaux1
