# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_c_compilerclangfortran_compilergfortran
    - CONFIG=osx_c_compilertoolchain_cfortran_compilertoolchain_fort

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "ZyDTkFZbYfo+WCemo87xuXlU2kcejJbkd16rouBJtZ4ow+qRcrKxjczXrKlLoJY5EwzK2fxVGCFZJ3oWMUfFq9aRwo7GoEYE6ymB9GFuZ5HePsqtESnyjGJGnIRs87QeJseZYipvpAT46pBOoRCPbXxhukIqFqdcXq6wo/WhgVXU8ob6KUhq10GndgIUSMU3ZmkyJ+hWSKFLF4T6s4ZxU8igZ10OW7bpDDfVMImXg1EyJgc8yb/t7tlzfn0F8EhYqluiWYaaBSRtPbKohgVNy53lPY81bZCBblb4DaXhkvZNzoGRA+kJ1F7OqvjJNucDuOz1ybU6MO6Myl+Hcf874kNWidgVn2X//NVtjYPyTXF2iXMTTDGglf+5b0jQWqQuOnvKM2fKnxrYd6a2j4aiH6mGuLo59OqHA0fffUznH9sTtTjJOxgszJK34Idi1NCMsieAXshMuDIhrF+08037Y5BjHkf7ilnRAs80qlAz/nkJ/urHPNn1Ig5+ieoHgYxoZu9yx+pCw8SddAtCYlFBvM1oIvziHHPF/+JF8IPpRrg9XKe+x6sAM6WfHfym+WRYnCW4AxkIm3R8IXheqwHFjb+GcVaGSjAW7/iBZURGW+1KH47aM3Zwi60NnwmD4igCZTDmldOrq3i/LfV7zWau1a5sqRuSeLuFJ5hYZb9TCXs="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
