appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: ZyDTkFZbYfo+WCemo87xuXlU2kcejJbkd16rouBJtZ4ow+qRcrKxjczXrKlLoJY5EwzK2fxVGCFZJ3oWMUfFq9aRwo7GoEYE6ymB9GFuZ5HePsqtESnyjGJGnIRs87QeJseZYipvpAT46pBOoRCPbXxhukIqFqdcXq6wo/WhgVXU8ob6KUhq10GndgIUSMU3ZmkyJ+hWSKFLF4T6s4ZxU8igZ10OW7bpDDfVMImXg1EyJgc8yb/t7tlzfn0F8EhYqluiWYaaBSRtPbKohgVNy53lPY81bZCBblb4DaXhkvZNzoGRA+kJ1F7OqvjJNucDuOz1ybU6MO6Myl+Hcf874kNWidgVn2X//NVtjYPyTXF2iXMTTDGglf+5b0jQWqQuOnvKM2fKnxrYd6a2j4aiH6mGuLo59OqHA0fffUznH9sTtTjJOxgszJK34Idi1NCMsieAXshMuDIhrF+08037Y5BjHkf7ilnRAs80qlAz/nkJ/urHPNn1Ig5+ieoHgYxoZu9yx+pCw8SddAtCYlFBvM1oIvziHHPF/+JF8IPpRrg9XKe+x6sAM6WfHfym+WRYnCW4AxkIm3R8IXheqwHFjb+GcVaGSjAW7/iBZURGW+1KH47aM3Zwi60NnwmD4igCZTDmldOrq3i/LfV7zWau1a5sqRuSeLuFJ5hYZb9TCXs=}
